### ISSUE TITLE
Documentation link is wrong

### ISSUE THREAD

**Issue by Dr-Emann** [mjc-gh/rev_lines#2]
The documentation link in [Cargo.toml](https://github.com/mikeycgto/rev_lines/blob/188d5cafe7f0f18ec3c3ae52eae2108a89aafa68/Cargo.toml#L6) does not point to the documentation for this library.

**Comment by mjc-gh** [comment]
Fixed: https://crates.io/crates/rev_lines

Thanks for reporting this!
