### ISSUE TITLE
[Q] Can this lib solve this use case?

### ISSUE THREAD

**Issue by NightMachinery** [mjc-gh/rev_lines#4]
https://users.rust-lang.org/t/count-trailing-zero-bytes-of-a-binary-file/42503/2

```
use std::env;
use std::fs;

fn main() {
    let filename = env::args().nth(1).unwrap();
    let buffer = fs::read(filename).unwrap();
    let count = buffer.iter().rev().take_while(|b| **b == 0).count();
    println!("{}", count);
}
```

There are no new lines as the file is binary.

**Comment by mjc-gh** [comment]
This library would likely not support this use case. Feel free to open a PR to add some support. Thanks!
