### ISSUE TITLE
[Q] Is it possible to use rev_lines and the regular order interchangeably?

### ISSUE THREAD

**Issue by yctwo** [mjc-gh/rev_lines#5]
I'm trying to do the following:
```
    let lines = if something_is_true {
        RevLines::new(BufReader::new(file)).unwrap()
    } else {
        BufReader::new(file).lines()
    };
```
However, this is not a valid Rust syntax since the types are incompatible for the `if` and `else` arm. Any suggestions?

**Comment by mjc-gh** [comment]
Not sure I have a good solution to this specific use case without seeing more code. Closing this for now.
